const img = (id, w = 1600) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`

const allInclusive =
  'Per-person rate, all-inclusive: Sustainable Development Fee, hotels, all meals, licensed guide, private transport & entry fees. International flights excluded.'

export const tourPackages = {
  // ============ Trekking Tours ============
  'druk-path-trek': {
    name: 'Druk Path Trek',
    tour: 'Trekking Tours',
    tourPath: '/trekking-tours',
    tagline: 'Bhutan\u2019s classic high-lake trek between Paro and Thimphu',
    heroImage: '/images/tours/drukpath%20trek.jpg',
    duration: '6 Days / 5 Nights',
    groupSize: '2\u201310 trekkers',
    bestSeason: 'Apr\u2013Jun & Sep\u2013Nov',
    overview:
      'One of the most popular treks in Bhutan, the Druk Path links Paro and Thimphu over a high ridge dotted with crystal-clear lakes, ancient lhakhangs and rhododendron forest. Moderate in difficulty with spectacular Himalayan views, it is the perfect short trek for first-time mountain walkers.',
    pricingNote: allInclusive,
    pricing: [
      { group: '2 Trekkers', price: '$2,150', unit: 'per person' },
      { group: '3\u20135 Trekkers', price: '$1,950', unit: 'per person' },
      { group: '6+ Trekkers', price: '$1,800', unit: 'per person' },
    ],
    highlights: [
      'High-altitude lakes including Jimilang Tsho',
      'Panoramic views of Mount Gangkhar Puensum',
      'Ancient Jele Dzong',
      'Pristine rhododendron and blue pine forest',
      'Full camping crew with cook and ponies',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Arrival, gear check and acclimatisation in Paro valley.' },
      { day: 'Day 2', title: 'Paro to Jele Dzong', desc: 'Begin the climb to Jele Dzong (3,480 m) with valley views.' },
      { day: 'Day 3', title: 'Jele Dzong to Jangchulakha', desc: 'Ridge walking through forest with yak herder camps.' },
      { day: 'Day 4', title: 'Jangchulakha to Jimilang Tsho', desc: 'Trek to the famous trout-filled lake (3,880 m).' },
      { day: 'Day 5', title: 'Descend to Thimphu', desc: 'Cross Simkota and descend to Thimphu; transfer to hotel.' },
      { day: 'Day 6', title: 'Departure', desc: 'Drive to Paro airport for your onward flight.' },
    ],
  },
  'jomolhari-trek': {
    name: 'Jomolhari Trek',
    tour: 'Trekking Tours',
    tourPath: '/trekking-tours',
    tagline: 'A challenging journey to the base of sacred Mount Jomolhari',
    heroImage: '/images/tours/jomolhari%20trek.jpg',
    duration: '9 Days / 8 Nights',
    groupSize: '2\u20138 trekkers',
    bestSeason: 'Apr\u2013Jun & Sep\u2013Oct',
    overview:
      'Trek to the foot of the holy 7,326 m Mount Jomolhari, one of the most rewarding routes in the Himalayas. Pass through remote villages, army outposts and high pastures, camping beneath towering snow peaks at Jangothang base camp with chances to spot blue sheep and Himalayan wildlife.',
    pricingNote: allInclusive,
    pricing: [
      { group: '2 Trekkers', price: '$3,250', unit: 'per person' },
      { group: '3\u20135 Trekkers', price: '$2,950', unit: 'per person' },
      { group: '6+ Trekkers', price: '$2,750', unit: 'per person' },
    ],
    highlights: [
      'Jangothang base camp beneath Mount Jomolhari',
      'High pass crossing at Nyile La (4,890 m)',
      'Remote villages and yak herder life',
      'Blue sheep and Himalayan wildlife',
      'Lingshi Dzong and alpine meadows',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Arrival and trek briefing in Paro.' },
      { day: 'Day 2', title: 'Paro Acclimatisation', desc: 'Tiger\u2019s Nest hike to aid acclimatisation.' },
      { day: 'Day 3', title: 'Drukgyel Dzong to Shana', desc: 'Trailhead start following the Paro Chhu river.' },
      { day: 'Day 4', title: 'Shana to Soi Thangthangkha', desc: 'Long forest day with the first views of Jomolhari.' },
      { day: 'Day 5', title: 'To Jangothang Base Camp', desc: 'Climb to the spectacular base camp (4,080 m).' },
      { day: 'Day 6', title: 'Jangothang Rest Day', desc: 'Acclimatisation day hikes and wildlife spotting.' },
      { day: 'Day 7', title: 'Jangothang to Lingshi', desc: 'Cross Nyile La pass (4,890 m) to Lingshi.' },
      { day: 'Day 8', title: 'Trek Out & Drive', desc: 'Descend to the road head and drive to Paro.' },
      { day: 'Day 9', title: 'Departure', desc: 'Transfer to Paro airport for your onward flight.' },
    ],
  },
  'snowman-trek': {
    name: 'Snowman Trek',
    tour: 'Trekking Tours',
    tourPath: '/trekking-tours',
    tagline: 'The legendary expedition across remote Lunana \u2014 one of the world\u2019s hardest treks',
    heroImage: '/images/tours/trekking%20herobanner.jpg',
    duration: '25 Days / 24 Nights',
    groupSize: '2\u20136 trekkers',
    bestSeason: 'Late Sep\u2013Oct',
    overview:
      'The Snowman Trek is widely regarded as one of the most difficult and rewarding treks on earth. Crossing eleven high passes \u2014 many above 5,000 m \u2014 it links the Jomolhari region with the utterly remote Lunana district. This is a true Himalayan expedition for fit, experienced trekkers seeking the journey of a lifetime.',
    pricingNote: allInclusive,
    pricing: [
      { group: '2 Trekkers', price: '$8,200', unit: 'per person' },
      { group: '3\u20135 Trekkers', price: '$7,500', unit: 'per person' },
      { group: '6 Trekkers', price: '$7,100', unit: 'per person' },
    ],
    highlights: [
      'Eleven high passes, several above 5,000 m',
      'The remote Lunana district',
      'Glacial lakes and towering 7,000 m peaks',
      'Authentic, rarely-visited highland villages',
      'A full expedition crew and support team',
    ],
    itinerary: [
      { day: 'Days 1\u20132', title: 'Arrive & Acclimatise', desc: 'Paro arrival, briefing and Tiger\u2019s Nest acclimatisation hike.' },
      { day: 'Days 3\u20136', title: 'Jomolhari Stage', desc: 'Trek via Shana and Soi Thangthangkha to Jangothang base camp.' },
      { day: 'Days 7\u201310', title: 'Lingshi to Laya', desc: 'Cross high passes through Lingshi and Chebisa to the village of Laya.' },
      { day: 'Days 11\u201316', title: 'Into Lunana', desc: 'The crux of the trek \u2014 multiple 5,000 m passes into remote Lunana.' },
      { day: 'Days 17\u201322', title: 'Lunana to Sephu', desc: 'Cross the final high passes and descend toward the road at Sephu.' },
      { day: 'Days 23\u201324', title: 'Drive to Thimphu/Paro', desc: 'Long scenic drives back to the western valleys with a celebration dinner.' },
      { day: 'Day 25', title: 'Departure', desc: 'Transfer to Paro airport for your onward flight.' },
    ],
  },

  // ============ Cultural Tours ============
  'glimpses-of-bhutan': {
    name: 'Glimpses of Bhutan',
    tour: 'Cultural Tours',
    tourPath: '/cultural-tours',
    tagline: 'A perfect 5-day first taste of the Thunder Dragon Kingdom',
    heroImage: '/images/tours/Thimphu.jpg',
    duration: '5 Days / 4 Nights',
    groupSize: '1\u201312 guests',
    bestSeason: 'Mar\u2013May & Sep\u2013Nov',
    overview:
      'The ideal introduction to Bhutan, this short journey takes you through the two most iconic valleys \u2014 Paro and Thimphu. Hike to the legendary Tiger\u2019s Nest, explore fortress dzongs and ancient temples, and experience the gentle rhythm of Bhutanese life, all at a relaxed and comfortable pace.',
    pricingNote: allInclusive,
    pricing: [
      { group: 'Solo Traveller', price: '$1,450', unit: 'per person' },
      { group: '2 Travellers', price: '$1,250', unit: 'per person' },
      { group: '3\u20135 Travellers', price: '$1,150', unit: 'per person' },
      { group: '6+ Travellers', price: '$1,050', unit: 'per person' },
    ],
    highlights: [
      'Hike to the iconic Tiger\u2019s Nest Monastery',
      'Explore Rinpung Dzong and Paro\u2019s old town',
      'Visit the giant Buddha Dordenma in Thimphu',
      'Spin prayer wheels at the National Memorial Chorten',
      'Meet the takin, Bhutan\u2019s national animal',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Scenic Himalayan flight into Paro, visit Rinpung Dzong and stroll the old town.' },
      { day: 'Day 2', title: 'Tiger\u2019s Nest Hike', desc: 'Trek up to the cliff-side Taktsang Monastery, then visit sacred Kyichu Lhakhang.' },
      { day: 'Day 3', title: 'Paro to Thimphu', desc: 'Drive to the capital and visit the Buddha Dordenma and Memorial Chorten.' },
      { day: 'Day 4', title: 'Thimphu Sightseeing', desc: 'Tashichho Dzong, the weekend market and the Motithang takin preserve.' },
      { day: 'Day 5', title: 'Departure', desc: 'Transfer to Paro airport for your onward flight.' },
    ],
  },
  'cultural-heart-of-bhutan': {
    name: 'Cultural Heart of Bhutan',
    tour: 'Cultural Tours',
    tourPath: '/cultural-tours',
    tagline: 'Eight immersive days through Paro, Thimphu and Punakha',
    heroImage: '/images/home/herobanner1.jpg',
    duration: '8 Days / 7 Nights',
    groupSize: '1\u201312 guests',
    bestSeason: 'Mar\u2013May & Sep\u2013Nov',
    overview:
      'Go deeper into Bhutan\u2019s living culture on this classic journey across three magnificent valleys. Cross the prayer-flag-draped Dochula Pass, witness the grandeur of Punakha Dzong at the meeting of two rivers, and immerse yourself in the temples, markets and traditions of the western heartland.',
    pricingNote: allInclusive,
    pricing: [
      { group: 'Solo Traveller', price: '$2,250', unit: 'per person' },
      { group: '2 Travellers', price: '$1,950', unit: 'per person' },
      { group: '3\u20135 Travellers', price: '$1,800', unit: 'per person' },
      { group: '6+ Travellers', price: '$1,650', unit: 'per person' },
    ],
    highlights: [
      'Majestic Punakha Dzong between two rivers',
      'Tiger\u2019s Nest Monastery hike',
      '108 chortens and Himalayan views at Dochula Pass',
      'Chimi Lhakhang, the fertility temple',
      'Punakha suspension bridge walk',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Welcome at the airport and transfer to your hotel; evening at leisure.' },
      { day: 'Day 2', title: 'Tiger\u2019s Nest Hike', desc: 'Hike to Taktsang Monastery and explore Paro valley.' },
      { day: 'Day 3', title: 'Paro to Thimphu', desc: 'Drive to the capital, visit the Buddha Dordenma and city sights.' },
      { day: 'Day 4', title: 'Thimphu Sightseeing', desc: 'Tashichho Dzong, craft schools, weekend market and takin preserve.' },
      { day: 'Day 5', title: 'Thimphu to Punakha', desc: 'Cross Dochula Pass (3,100 m) to the warm Punakha valley.' },
      { day: 'Day 6', title: 'Punakha Discovery', desc: 'Punakha Dzong, the suspension bridge and a walk to Chimi Lhakhang.' },
      { day: 'Day 7', title: 'Punakha to Paro', desc: 'Return drive to Paro with stops along the way.' },
      { day: 'Day 8', title: 'Departure', desc: 'Transfer to Paro airport for your onward flight.' },
    ],
  },
  'western-bhutan-discovery': {
    name: 'Western Bhutan Discovery',
    tour: 'Cultural Tours',
    tourPath: '/cultural-tours',
    tagline: 'Seven days of dzongs, temples and dramatic valleys',
    heroImage: '/images/tours/thimphu1.jpg',
    duration: '7 Days / 6 Nights',
    groupSize: '1\u201312 guests',
    bestSeason: 'Mar\u2013May & Sep\u2013Nov',
    overview:
      'A well-rounded exploration of western Bhutan\u2019s greatest hits, from the airport gateway of Paro to the riverside fortress of Punakha. Discover fortress architecture, sacred temples and sweeping mountain scenery, with time to slow down and connect with local life.',
    pricingNote: allInclusive,
    pricing: [
      { group: 'Solo Traveller', price: '$1,950', unit: 'per person' },
      { group: '2 Travellers', price: '$1,700', unit: 'per person' },
      { group: '3\u20135 Travellers', price: '$1,550', unit: 'per person' },
      { group: '6+ Travellers', price: '$1,450', unit: 'per person' },
    ],
    highlights: [
      'Tiger\u2019s Nest Monastery hike',
      'Dochula Pass and its 108 chortens',
      'Punakha Dzong and suspension bridge',
      'Historic Drukgyel Dzong ruins',
      'Authentic farmhouse visit',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Scenic flight into Paro and a gentle valley orientation.' },
      { day: 'Day 2', title: 'Tiger\u2019s Nest Hike', desc: 'Trek to Taktsang and visit Drukgyel Dzong and Kyichu Lhakhang.' },
      { day: 'Day 3', title: 'Paro to Thimphu', desc: 'Drive to the capital for city sightseeing.' },
      { day: 'Day 4', title: 'Thimphu to Punakha', desc: 'Cross Dochula Pass to the subtropical Punakha valley.' },
      { day: 'Day 5', title: 'Punakha Sightseeing', desc: 'Punakha Dzong, suspension bridge and Chimi Lhakhang.' },
      { day: 'Day 6', title: 'Punakha to Paro', desc: 'Return to Paro with a farmhouse visit en route.' },
      { day: 'Day 7', title: 'Departure', desc: 'Transfer to Paro airport for your onward flight.' },
    ],
  },

  // ============ Pilgrimage Tours ============
  'sacred-sites-pilgrimage': {
    name: 'Sacred Sites Pilgrimage',
    tour: 'Pilgrimage Tours',
    tourPath: '/pilgrimage-tours',
    tagline: 'Seven days visiting Bhutan\u2019s holiest temples and dzongs',
    heroImage: img('photo-1570366583862-f91883984fde'),
    duration: '7 Days / 6 Nights',
    groupSize: '1\u201312 pilgrims',
    bestSeason: 'Mar\u2013May & Sep\u2013Nov',
    overview:
      'A devotional journey to the most sacred sites of western Bhutan, from the cliff-clinging Tiger\u2019s Nest to the blessed temples of Punakha. With time for prayer, butter-lamp offerings and quiet reflection, this pilgrimage nourishes both body and spirit.',
    pricingNote: allInclusive,
    pricing: [
      { group: 'Solo Traveller', price: '$1,950', unit: 'per person' },
      { group: '2 Travellers', price: '$1,700', unit: 'per person' },
      { group: '3\u20135 Travellers', price: '$1,550', unit: 'per person' },
      { group: '6+ Travellers', price: '$1,450', unit: 'per person' },
    ],
    highlights: [
      'Pilgrimage to the Tiger\u2019s Nest Monastery',
      'Butter-lamp offerings at Kyichu Lhakhang',
      'Blessings at Chimi Lhakhang',
      'Prayers at Punakha Dzong',
      'Sacred Memorial Chorten in Thimphu',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Arrival and an opening blessing at Kyichu Lhakhang.' },
      { day: 'Day 2', title: 'Tiger\u2019s Nest Pilgrimage', desc: 'Sacred hike to Taktsang Monastery for prayer and offerings.' },
      { day: 'Day 3', title: 'Paro to Thimphu', desc: 'Visit the Memorial Chorten and Buddha Dordenma.' },
      { day: 'Day 4', title: 'Thimphu to Punakha', desc: 'Cross Dochula Pass and pray at Chimi Lhakhang.' },
      { day: 'Day 5', title: 'Punakha Dzong', desc: 'Devotions at the magnificent riverside fortress.' },
      { day: 'Day 6', title: 'Return to Paro', desc: 'Final temple visits and reflection en route.' },
      { day: 'Day 7', title: 'Departure', desc: 'Transfer to Paro airport for your onward flight.' },
    ],
  },
  'guru-rinpoche-trail': {
    name: 'Guru Rinpoche Trail',
    tour: 'Pilgrimage Tours',
    tourPath: '/pilgrimage-tours',
    tagline: 'Nine days in the footsteps of the saint who brought Buddhism to Bhutan',
    heroImage: img('photo-1567604130959-7ea7ab2a7807'),
    duration: '9 Days / 8 Nights',
    groupSize: '1\u201312 pilgrims',
    bestSeason: 'Mar\u2013May & Sep\u2013Nov',
    overview:
      'Follow the legendary trail of Guru Rinpoche from the western valleys to the spiritual heartland of Bumthang. Visit the caves and temples where he meditated and subdued demons, deepening your understanding of Bhutan\u2019s living Buddhist faith.',
    pricingNote: allInclusive,
    pricing: [
      { group: 'Solo Traveller', price: '$2,650', unit: 'per person' },
      { group: '2 Travellers', price: '$2,350', unit: 'per person' },
      { group: '3\u20135 Travellers', price: '$2,150', unit: 'per person' },
      { group: '6+ Travellers', price: '$1,950', unit: 'per person' },
    ],
    highlights: [
      'Tiger\u2019s Nest, where Guru Rinpoche meditated',
      'Sacred Kurjey Lhakhang in Bumthang',
      'Holy Membartsho (Burning Lake)',
      'Ancient Jambay Lhakhang',
      'Quiet time for prayer and ritual',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Arrival and opening blessings.' },
      { day: 'Day 2', title: 'Tiger\u2019s Nest', desc: 'Pilgrimage hike to the saint\u2019s meditation site.' },
      { day: 'Day 3', title: 'Paro to Thimphu', desc: 'Sacred sites of the capital.' },
      { day: 'Day 4', title: 'Thimphu to Punakha', desc: 'Dochula Pass and Chimi Lhakhang.' },
      { day: 'Day 5', title: 'Punakha to Bumthang', desc: 'Scenic flight or drive to the spiritual heartland.' },
      { day: 'Day 6', title: 'Kurjey & Jambay Lhakhang', desc: 'Visit the holiest temples linked to Guru Rinpoche.' },
      { day: 'Day 7', title: 'Membartsho', desc: 'Pilgrimage to the sacred Burning Lake.' },
      { day: 'Day 8', title: 'Return West', desc: 'Travel back toward Paro with reflection time.' },
      { day: 'Day 9', title: 'Departure', desc: 'Transfer to Paro airport for your onward flight.' },
    ],
  },
  'bumthang-spiritual-circuit': {
    name: 'Bumthang Spiritual Circuit',
    tour: 'Pilgrimage Tours',
    tourPath: '/pilgrimage-tours',
    tagline: 'Eight days exploring the religious heartland of Bhutan',
    heroImage: img('photo-1605640840605-14ac1855827b'),
    duration: '8 Days / 7 Nights',
    groupSize: '1\u201312 pilgrims',
    bestSeason: 'Mar\u2013May & Sep\u2013Nov',
    overview:
      'Bumthang\u2019s four sacred valleys hold many of Bhutan\u2019s oldest and holiest temples. This circuit immerses you in centuries of pilgrimage tradition, with gentle temple walks, prayer ceremonies and the serene beauty of central Bhutan.',
    pricingNote: allInclusive,
    pricing: [
      { group: 'Solo Traveller', price: '$2,450', unit: 'per person' },
      { group: '2 Travellers', price: '$2,150', unit: 'per person' },
      { group: '3\u20135 Travellers', price: '$1,950', unit: 'per person' },
      { group: '6+ Travellers', price: '$1,800', unit: 'per person' },
    ],
    highlights: [
      'The four sacred valleys of Bumthang',
      'Jakar Dzong and Jambay Lhakhang',
      'Kurjey Lhakhang complex',
      'Tamshing Lhakhang frescoes',
      'Holy Membartsho lake',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Arrival and transfer to your hotel.' },
      { day: 'Day 2', title: 'Fly to Bumthang', desc: 'Scenic Himalayan flight to central Bhutan.' },
      { day: 'Day 3', title: 'Jakar & Jambay', desc: 'Visit the dzong and the 7th-century Jambay Lhakhang.' },
      { day: 'Day 4', title: 'Kurjey & Tamshing', desc: 'Sacred complexes and ancient murals.' },
      { day: 'Day 5', title: 'Membartsho', desc: 'Pilgrimage to the Burning Lake and Tang valley.' },
      { day: 'Day 6', title: 'Ura Valley', desc: 'Gentle temple walk in the highest Bumthang valley.' },
      { day: 'Day 7', title: 'Return to Paro', desc: 'Fly back west for final reflection.' },
      { day: 'Day 8', title: 'Departure', desc: 'Transfer to Paro airport for your onward flight.' },
    ],
  },

  // ============ Birding Tours ============
  'spring-birding-expedition': {
    name: 'Spring Birding Expedition',
    tour: 'Birding Tours',
    tourPath: '/birding-tours',
    tagline: 'Ten days of peak-season birding across Bhutan\u2019s richest habitats',
    heroImage: img('photo-1540541338287-41700207dee6'),
    duration: '10 Days / 9 Nights',
    groupSize: '2\u20138 birders',
    bestSeason: 'Mar\u2013May',
    overview:
      'Spring is prime time for birding in Bhutan, when migrants return and resident species are in full breeding plumage. This expedition crosses forest, river and high-pass habitats with expert guides, targeting hundreds of species including many Himalayan specialities.',
    pricingNote: allInclusive,
    pricing: [
      { group: '2 Birders', price: '$3,150', unit: 'per person' },
      { group: '3\u20135 Birders', price: '$2,850', unit: 'per person' },
      { group: '6+ Birders', price: '$2,650', unit: 'per person' },
    ],
    highlights: [
      'Hundreds of Himalayan bird species',
      'Rufous-necked hornbill sightings',
      'Colourful Himalayan monal',
      'Expert local bird guides',
      'Birding across multiple habitats',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Arrival and first valley birding.' },
      { day: 'Days 2\u20133', title: 'Paro & Thimphu', desc: 'Forest trails and riverbank birding around the western valleys.' },
      { day: 'Days 4\u20135', title: 'Dochula & Punakha', desc: 'High-pass and subtropical species.' },
      { day: 'Days 6\u20137', title: 'Phobjikha Valley', desc: 'Wetland birding and crane habitat.' },
      { day: 'Days 8\u20139', title: 'Trongsa Forests', desc: 'Old-growth forest birding for rare endemics.' },
      { day: 'Day 10', title: 'Departure', desc: 'Return to Paro for your onward flight.' },
    ],
  },
  'black-necked-crane-watch': {
    name: 'Black-Necked Crane Watch',
    tour: 'Birding Tours',
    tourPath: '/birding-tours',
    tagline: 'Six days witnessing the rare cranes of Phobjikha Valley',
    heroImage: img('photo-1455587734955-081b22074882'),
    duration: '6 Days / 5 Nights',
    groupSize: '2\u201310 birders',
    bestSeason: 'Nov\u2013Feb',
    overview:
      'Every winter, hundreds of rare black-necked cranes migrate from the Tibetan plateau to the glacial Phobjikha Valley. This journey times your visit to the heart of crane season, combining unforgettable wildlife watching with the cultural charm of central Bhutan.',
    pricingNote: allInclusive,
    pricing: [
      { group: '2 Birders', price: '$1,750', unit: 'per person' },
      { group: '3\u20135 Birders', price: '$1,550', unit: 'per person' },
      { group: '6+ Birders', price: '$1,400', unit: 'per person' },
    ],
    highlights: [
      'Hundreds of black-necked cranes',
      'The Black-Necked Crane Centre',
      'Gangtey Monastery and valley',
      'Gentle nature-trail birding',
      'Dochula Pass Himalayan views',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Arrival and transfer to Thimphu.' },
      { day: 'Day 2', title: 'Thimphu to Phobjikha', desc: 'Cross Dochula Pass to the crane valley.' },
      { day: 'Day 3', title: 'Crane Watching', desc: 'Full day observing cranes and valley birds.' },
      { day: 'Day 4', title: 'Gangtey & Nature Trail', desc: 'Monastery visit and gentle birding walk.' },
      { day: 'Day 5', title: 'Return to Paro', desc: 'Scenic drive back west.' },
      { day: 'Day 6', title: 'Departure', desc: 'Transfer to Paro airport for your onward flight.' },
    ],
  },
  'eastern-bhutan-birding': {
    name: 'Eastern Bhutan Birding',
    tour: 'Birding Tours',
    tourPath: '/birding-tours',
    tagline: 'Twelve days chasing endemics across the wild east',
    heroImage: img('photo-1464822759023-fed622ff2c3b'),
    duration: '12 Days / 11 Nights',
    groupSize: '2\u20138 birders',
    bestSeason: 'Mar\u2013Apr & Oct\u2013Nov',
    overview:
      'The remote east of Bhutan offers some of the finest birding in the Himalayas, with dense subtropical forests harbouring rare and endemic species. This in-depth expedition traverses the country east to west, maximising your species count along the way.',
    pricingNote: allInclusive,
    pricing: [
      { group: '2 Birders', price: '$3,950', unit: 'per person' },
      { group: '3\u20135 Birders', price: '$3,550', unit: 'per person' },
      { group: '6+ Birders', price: '$3,300', unit: 'per person' },
    ],
    highlights: [
      'Rare eastern endemics',
      'Dense subtropical forest birding',
      'Beautiful nuthatch and wren-babblers',
      'Remote, rarely-birded valleys',
      'Cross-country Himalayan scenery',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Arrival and orientation.' },
      { day: 'Days 2\u20133', title: 'Western Valleys', desc: 'Warm-up birding around Thimphu and Punakha.' },
      { day: 'Days 4\u20135', title: 'Trongsa & Bumthang', desc: 'Central forest birding.' },
      { day: 'Days 6\u20138', title: 'Into the East', desc: 'Mongar and Lingmethang road for prime endemics.' },
      { day: 'Days 9\u201311', title: 'Trashigang Region', desc: 'Subtropical forests and river valleys.' },
      { day: 'Day 12', title: 'Departure', desc: 'Fly out from the east or transfer onward.' },
    ],
  },

  // ============ Fly Fishing Tours ============
  'himalayan-trout-adventure': {
    name: 'Himalayan Trout Adventure',
    tour: 'Fly Fishing Tours',
    tourPath: '/fly-fishing-tours',
    tagline: 'Seven days chasing wild brown trout in pristine rivers',
    heroImage: img('photo-1506905925346-21bda4d32df4'),
    duration: '7 Days / 6 Nights',
    groupSize: '2\u20136 anglers',
    bestSeason: 'Mar\u2013May & Oct\u2013Nov',
    overview:
      'Fish some of the least-pressured waters on the planet on this guided fly-fishing adventure. Casting for wild brown trout in crystal-clear, glacier-fed rivers, you\u2019ll combine world-class catch-and-release angling with Bhutan\u2019s spectacular scenery and culture.',
    pricingNote: allInclusive + ' Fishing permits and guiding included; tackle available to hire.',
    pricing: [
      { group: '2 Anglers', price: '$2,650', unit: 'per person' },
      { group: '3\u20134 Anglers', price: '$2,350', unit: 'per person' },
      { group: '5\u20136 Anglers', price: '$2,150', unit: 'per person' },
    ],
    highlights: [
      'Wild brown trout in clear waters',
      'Expert local fishing guides',
      'Strict catch-and-release ethic',
      'Riverside picnics and scenery',
      'Cultural sightseeing between sessions',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Arrival, gear check and casting briefing.' },
      { day: 'Day 2', title: 'Paro River Session', desc: 'Fish the Paro Chhu with your guide.' },
      { day: 'Day 3', title: 'Transfer to Punakha', desc: 'Cross Dochula Pass to prime trout water.' },
      { day: 'Day 4', title: 'Mo Chhu Fishing', desc: 'Full day on the river chasing wild trout.' },
      { day: 'Day 5', title: 'Pho Chhu Fishing', desc: 'A second river day with a dzong visit.' },
      { day: 'Day 6', title: 'Return to Paro', desc: 'Scenic drive back and free time.' },
      { day: 'Day 7', title: 'Departure', desc: 'Transfer to Paro airport for your onward flight.' },
    ],
  },
  'mo-chhu-river-fishing': {
    name: 'Mo Chhu River Fishing',
    tour: 'Fly Fishing Tours',
    tourPath: '/fly-fishing-tours',
    tagline: 'Five focused days on Punakha\u2019s legendary river',
    heroImage: img('photo-1528181304800-259b08848526'),
    duration: '5 Days / 4 Nights',
    groupSize: '2\u20136 anglers',
    bestSeason: 'Mar\u2013May & Oct\u2013Nov',
    overview:
      'A short, focused angling escape to the beautiful Mo Chhu river beneath Punakha Dzong. With warm valley weather and clear waters, it\u2019s the perfect introduction to fly fishing in Bhutan for those short on time.',
    pricingNote: allInclusive + ' Fishing permits and guiding included; tackle available to hire.',
    pricing: [
      { group: '2 Anglers', price: '$1,850', unit: 'per person' },
      { group: '3\u20134 Anglers', price: '$1,650', unit: 'per person' },
      { group: '5\u20136 Anglers', price: '$1,500', unit: 'per person' },
    ],
    highlights: [
      'Fishing beneath Punakha Dzong',
      'Warm, scenic valley setting',
      'Wild trout in clear water',
      'Catch-and-release guiding',
      'Riverside relaxation',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive & Transfer', desc: 'Fly into Paro and drive to Punakha via Dochula.' },
      { day: 'Day 2', title: 'Mo Chhu Session', desc: 'Full day fishing the upper Mo Chhu.' },
      { day: 'Day 3', title: 'River & Dzong', desc: 'Morning fishing and a Punakha Dzong visit.' },
      { day: 'Day 4', title: 'Return to Paro', desc: 'Scenic drive back west.' },
      { day: 'Day 5', title: 'Departure', desc: 'Transfer to Paro airport for your onward flight.' },
    ],
  },
  'highland-lakes-fly-fishing': {
    name: 'Highland Lakes Fly Fishing',
    tour: 'Fly Fishing Tours',
    tourPath: '/fly-fishing-tours',
    tagline: 'Eight days reaching remote alpine waters',
    heroImage: img('photo-1464822759023-fed622ff2c3b'),
    duration: '8 Days / 7 Nights',
    groupSize: '2\u20136 anglers',
    bestSeason: 'Apr\u2013Jun & Sep\u2013Oct',
    overview:
      'For the adventurous angler, this journey ventures to remote highland lakes and rivers rarely touched by a fly. Combining light trekking with prime fishing, it rewards effort with pristine waters and the deep solitude of the Himalayas.',
    pricingNote: allInclusive + ' Fishing permits, guiding and camping support included.',
    pricing: [
      { group: '2 Anglers', price: '$3,250', unit: 'per person' },
      { group: '3\u20134 Anglers', price: '$2,950', unit: 'per person' },
      { group: '5\u20136 Anglers', price: '$2,750', unit: 'per person' },
    ],
    highlights: [
      'Remote alpine lakes and rivers',
      'Light trekking to untouched waters',
      'Wild trout in solitude',
      'Comfortable supported camps',
      'Spectacular high-country scenery',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Arrival and equipment briefing.' },
      { day: 'Day 2', title: 'Drive to Trailhead', desc: 'Transfer toward the highlands.' },
      { day: 'Days 3\u20134', title: 'Trek & Fish', desc: 'Walk to alpine waters and fish remote rivers.' },
      { day: 'Days 5\u20136', title: 'Lake Sessions', desc: 'Full days at pristine highland lakes.' },
      { day: 'Day 7', title: 'Return Journey', desc: 'Trek out and drive back to Paro.' },
      { day: 'Day 8', title: 'Departure', desc: 'Transfer to Paro airport for your onward flight.' },
    ],
  },

  // ============ Nature Tours ============
  'valleys-forests-discovery': {
    name: 'Valleys & Forests Discovery',
    tour: 'Nature Tours',
    tourPath: '/nature-tours',
    tagline: 'Eight days of scenic trails through Bhutan\u2019s living landscapes',
    heroImage: img('photo-1455587734955-081b22074882'),
    duration: '8 Days / 7 Nights',
    groupSize: '2\u201312 guests',
    bestSeason: 'Mar\u2013May & Sep\u2013Nov',
    overview:
      'Wander gently through glacial valleys and old-growth forest on this nature-focused journey. Walk among rhododendrons and prayer flags, watch for wildlife, and breathe the cleanest air on earth in the world\u2019s only carbon-negative country.',
    pricingNote: allInclusive,
    pricing: [
      { group: 'Solo Traveller', price: '$2,250', unit: 'per person' },
      { group: '2 Travellers', price: '$1,950', unit: 'per person' },
      { group: '3\u20135 Travellers', price: '$1,800', unit: 'per person' },
      { group: '6+ Travellers', price: '$1,650', unit: 'per person' },
    ],
    highlights: [
      'Scenic valley and forest trails',
      'Rhododendron blooms (in season)',
      'Wildlife and birdlife spotting',
      'Glacial Phobjikha Valley',
      'Pure Himalayan air',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Arrival and a gentle valley walk.' },
      { day: 'Day 2', title: 'Paro Nature Trails', desc: 'Forest walking and a Tiger\u2019s Nest hike.' },
      { day: 'Day 3', title: 'Paro to Thimphu', desc: 'Botanical garden and nature reserve.' },
      { day: 'Day 4', title: 'Dochula & Forests', desc: 'High-pass forest trails to Punakha.' },
      { day: 'Day 5', title: 'Punakha Valley Walk', desc: 'Riverside and rice-terrace trails.' },
      { day: 'Day 6', title: 'Phobjikha Valley', desc: 'Glacial valley nature trail and wetlands.' },
      { day: 'Day 7', title: 'Return to Paro', desc: 'Scenic drive back west.' },
      { day: 'Day 8', title: 'Departure', desc: 'Transfer to Paro airport for your onward flight.' },
    ],
  },
  'phobjikha-nature-escape': {
    name: 'Phobjikha Nature Escape',
    tour: 'Nature Tours',
    tourPath: '/nature-tours',
    tagline: 'Five tranquil days in a glacial valley',
    heroImage: img('photo-1540541338287-41700207dee6'),
    duration: '5 Days / 4 Nights',
    groupSize: '2\u201312 guests',
    bestSeason: 'Year-round',
    overview:
      'Escape to the wide, glacial Phobjikha Valley, one of Bhutan\u2019s most beautiful and ecologically important landscapes. Gentle nature trails, big skies and grazing yaks make this a restful immersion in Himalayan wilderness.',
    pricingNote: allInclusive,
    pricing: [
      { group: 'Solo Traveller', price: '$1,550', unit: 'per person' },
      { group: '2 Travellers', price: '$1,350', unit: 'per person' },
      { group: '3\u20135 Travellers', price: '$1,250', unit: 'per person' },
      { group: '6+ Travellers', price: '$1,150', unit: 'per person' },
    ],
    highlights: [
      'Glacial Phobjikha Valley',
      'Gangtey Nature Trail',
      'Wetlands and grazing yaks',
      'Dochula Pass views',
      'Peaceful highland scenery',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Arrival and transfer to Thimphu.' },
      { day: 'Day 2', title: 'To Phobjikha', desc: 'Cross Dochula Pass to the valley.' },
      { day: 'Day 3', title: 'Nature Trail', desc: 'Gangtey trail and wetland exploration.' },
      { day: 'Day 4', title: 'Return to Paro', desc: 'Scenic drive back west.' },
      { day: 'Day 5', title: 'Departure', desc: 'Transfer to Paro airport for your onward flight.' },
    ],
  },
  'himalayan-wilderness-tour': {
    name: 'Himalayan Wilderness Tour',
    tour: 'Nature Tours',
    tourPath: '/nature-tours',
    tagline: 'Ten days deep into Bhutan\u2019s national parks',
    heroImage: img('photo-1483728642387-6c3bdd6c93e5'),
    duration: '10 Days / 9 Nights',
    groupSize: '2\u201310 guests',
    bestSeason: 'Mar\u2013May & Sep\u2013Nov',
    overview:
      'An in-depth exploration of Bhutan\u2019s protected wilderness, from subtropical jungle to alpine meadow. Travel through national parks home to takins, red pandas and elusive snow leopards, with nature walks and wildlife watching throughout.',
    pricingNote: allInclusive,
    pricing: [
      { group: 'Solo Traveller', price: '$3,150', unit: 'per person' },
      { group: '2 Travellers', price: '$2,750', unit: 'per person' },
      { group: '3\u20135 Travellers', price: '$2,500', unit: 'per person' },
      { group: '6+ Travellers', price: '$2,300', unit: 'per person' },
    ],
    highlights: [
      'Multiple national parks and reserves',
      'Diverse habitats and wildlife',
      'Glacial valleys and forests',
      'Expert naturalist guiding',
      'Remote Himalayan scenery',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Arrival and orientation.' },
      { day: 'Days 2\u20133', title: 'Western Valleys', desc: 'Nature trails around Paro and Thimphu.' },
      { day: 'Days 4\u20135', title: 'Phobjikha', desc: 'Glacial valley wetlands and wildlife.' },
      { day: 'Days 6\u20137', title: 'Central Parks', desc: 'Forest trails toward Trongsa and Bumthang.' },
      { day: 'Days 8\u20139', title: 'Highland Trails', desc: 'Alpine meadows and wildlife watching.' },
      { day: 'Day 10', title: 'Departure', desc: 'Return to Paro for your onward flight.' },
    ],
  },

  // ============ Meditation Tours ============
  'mindful-bhutan-retreat': {
    name: 'Mindful Bhutan Retreat',
    tour: 'Meditation Tours',
    tourPath: '/meditation-tours',
    tagline: 'Seven days of guided meditation in sacred settings',
    heroImage: img('photo-1570366583862-f91883984fde'),
    duration: '7 Days / 6 Nights',
    groupSize: '2\u201312 guests',
    bestSeason: 'Year-round',
    overview:
      'Slow right down and turn inward on this gentle meditation retreat. Guided by experienced teachers, you\u2019ll practise daily in temples and tranquil settings, balancing sitting meditation with mindful walks and cultural reflection.',
    pricingNote: allInclusive + ' Meditation sessions and teacher guidance included.',
    pricing: [
      { group: 'Solo Traveller', price: '$2,150', unit: 'per person' },
      { group: '2 Travellers', price: '$1,850', unit: 'per person' },
      { group: '3\u20135 Travellers', price: '$1,700', unit: 'per person' },
      { group: '6+ Travellers', price: '$1,550', unit: 'per person' },
    ],
    highlights: [
      'Daily guided meditation',
      'Practice in sacred temples',
      'Mindful nature walks',
      'Teachings from local masters',
      'Time for quiet reflection',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Welcome and an opening evening meditation.' },
      { day: 'Day 2', title: 'Mindful Paro', desc: 'Morning practice and a gentle Tiger\u2019s Nest hike.' },
      { day: 'Day 3', title: 'Paro to Thimphu', desc: 'Temple meditation and a teacher session.' },
      { day: 'Day 4', title: 'Thimphu to Punakha', desc: 'Dochula Pass meditation and quiet valley time.' },
      { day: 'Day 5', title: 'Punakha Practice', desc: 'Riverside meditation and reflection.' },
      { day: 'Day 6', title: 'Return to Paro', desc: 'Closing practice and integration.' },
      { day: 'Day 7', title: 'Departure', desc: 'Transfer to Paro airport for your onward flight.' },
    ],
  },
  'monastery-meditation-journey': {
    name: 'Monastery Meditation Journey',
    tour: 'Meditation Tours',
    tourPath: '/meditation-tours',
    tagline: 'Nine days living and practising alongside monks',
    heroImage: img('photo-1567604130959-7ea7ab2a7807'),
    duration: '9 Days / 8 Nights',
    groupSize: '2\u201310 guests',
    bestSeason: 'Year-round',
    overview:
      'For a deeper immersion, this journey includes time staying near working monasteries, joining the daily rhythm of prayer and meditation. Experience monastic life first-hand while exploring the spiritual heart of Bhutan.',
    pricingNote: allInclusive + ' Meditation sessions and monastery visits included.',
    pricing: [
      { group: 'Solo Traveller', price: '$2,650', unit: 'per person' },
      { group: '2 Travellers', price: '$2,350', unit: 'per person' },
      { group: '3\u20135 Travellers', price: '$2,150', unit: 'per person' },
      { group: '6+ Travellers', price: '$1,950', unit: 'per person' },
    ],
    highlights: [
      'Practice alongside monks',
      'Daily meditation and prayer',
      'Visits to historic monasteries',
      'Teachings on Buddhist philosophy',
      'Deep peace and stillness',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Arrival and opening meditation.' },
      { day: 'Day 2', title: 'Tiger\u2019s Nest', desc: 'Mindful pilgrimage to the cliffside monastery.' },
      { day: 'Day 3', title: 'Paro to Thimphu', desc: 'Monastery visit and evening practice.' },
      { day: 'Days 4\u20135', title: 'Punakha Monastery Time', desc: 'Join the daily rhythm of prayer and meditation.' },
      { day: 'Days 6\u20137', title: 'Bumthang Sacred Sites', desc: 'Practice in central Bhutan\u2019s holiest temples.' },
      { day: 'Day 8', title: 'Return West', desc: 'Travel back with reflection time.' },
      { day: 'Day 9', title: 'Departure', desc: 'Transfer to Paro airport for your onward flight.' },
    ],
  },
  'silent-valley-retreat': {
    name: 'Silent Valley Retreat',
    tour: 'Meditation Tours',
    tourPath: '/meditation-tours',
    tagline: 'Six days of deep stillness in a tranquil valley',
    heroImage: img('photo-1506905925346-21bda4d32df4'),
    duration: '6 Days / 5 Nights',
    groupSize: '2\u201310 guests',
    bestSeason: 'Year-round',
    overview:
      'A restorative retreat centred on silence and simplicity in one of Bhutan\u2019s most peaceful valleys. With guided practice, mindful meals and gentle walks, it\u2019s a chance to truly unplug and reset.',
    pricingNote: allInclusive + ' Meditation sessions and teacher guidance included.',
    pricing: [
      { group: 'Solo Traveller', price: '$1,850', unit: 'per person' },
      { group: '2 Travellers', price: '$1,600', unit: 'per person' },
      { group: '3\u20135 Travellers', price: '$1,450', unit: 'per person' },
      { group: '6+ Travellers', price: '$1,350', unit: 'per person' },
    ],
    highlights: [
      'Periods of guided silence',
      'Tranquil valley setting',
      'Mindful, nourishing meals',
      'Gentle meditation walks',
      'Complete digital unplug',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Welcome and orientation to the retreat.' },
      { day: 'Day 2', title: 'Settle In', desc: 'First full day of guided practice and silence.' },
      { day: 'Day 3', title: 'Deep Practice', desc: 'Meditation, walking and reflection.' },
      { day: 'Day 4', title: 'Gentle Exploration', desc: 'Mindful nature walk and temple visit.' },
      { day: 'Day 5', title: 'Integration', desc: 'Closing sessions and quiet reflection.' },
      { day: 'Day 6', title: 'Departure', desc: 'Transfer to Paro airport for your onward flight.' },
    ],
  },

  // ============ Yoga Tours ============
  'himalayan-yoga-retreat': {
    name: 'Himalayan Yoga Retreat',
    tour: 'Yoga Tours',
    tourPath: '/yoga-tours',
    tagline: 'Seven days of daily practice in pure mountain air',
    heroImage: img('photo-1540541338287-41700207dee6'),
    duration: '7 Days / 6 Nights',
    groupSize: '4\u201314 guests',
    bestSeason: 'Mar\u2013May & Sep\u2013Nov',
    overview:
      'Deepen your practice surrounded by the Himalayas. With daily yoga sessions led by experienced instructors, wholesome cuisine and gentle cultural exploration, this retreat refreshes body and mind in one of the world\u2019s most serene settings.',
    pricingNote: allInclusive + ' Daily yoga classes and instruction included.',
    pricing: [
      { group: 'Solo Traveller', price: '$2,150', unit: 'per person' },
      { group: '2 Travellers', price: '$1,850', unit: 'per person' },
      { group: '3\u20135 Travellers', price: '$1,700', unit: 'per person' },
      { group: '6+ Travellers', price: '$1,550', unit: 'per person' },
    ],
    highlights: [
      'Daily morning and evening yoga',
      'Practice in Himalayan settings',
      'Meditation and breathwork',
      'Wholesome wellness cuisine',
      'Gentle cultural sightseeing',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Welcome and a restorative evening session.' },
      { day: 'Day 2', title: 'Paro Practice', desc: 'Morning flow and a gentle Tiger\u2019s Nest hike.' },
      { day: 'Day 3', title: 'Paro to Thimphu', desc: 'Yoga, city visit and evening practice.' },
      { day: 'Day 4', title: 'Thimphu to Punakha', desc: 'Dochula Pass and a riverside session.' },
      { day: 'Day 5', title: 'Punakha Yoga', desc: 'Valley flow and wellness time.' },
      { day: 'Day 6', title: 'Return to Paro', desc: 'Closing practice and integration.' },
      { day: 'Day 7', title: 'Departure', desc: 'Transfer to Paro airport for your onward flight.' },
    ],
  },
  'yoga-wellness-escape': {
    name: 'Yoga & Wellness Escape',
    tour: 'Yoga Tours',
    tourPath: '/yoga-tours',
    tagline: 'Six days blending yoga, spa and serenity',
    heroImage: img('photo-1506905925346-21bda4d32df4'),
    duration: '6 Days / 5 Nights',
    groupSize: '2\u201312 guests',
    bestSeason: 'Year-round',
    overview:
      'A nurturing blend of yoga, spa rituals and mindful relaxation. Combine daily practice with hot-stone baths, massage and healthy cuisine for a true reset amid the calm of the Bhutanese Himalayas.',
    pricingNote: allInclusive + ' Daily yoga and selected spa treatments included.',
    pricing: [
      { group: 'Solo Traveller', price: '$2,250', unit: 'per person' },
      { group: '2 Travellers', price: '$1,950', unit: 'per person' },
      { group: '3\u20135 Travellers', price: '$1,800', unit: 'per person' },
      { group: '6+ Travellers', price: '$1,650', unit: 'per person' },
    ],
    highlights: [
      'Daily yoga sessions',
      'Traditional hot-stone baths',
      'Spa and massage treatments',
      'Healthy, local cuisine',
      'Mindful relaxation time',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Welcome, wellness intro and first session.' },
      { day: 'Day 2', title: 'Yoga & Spa', desc: 'Morning flow and an afternoon hot-stone bath.' },
      { day: 'Day 3', title: 'Mindful Movement', desc: 'Gentle hike and restorative practice.' },
      { day: 'Day 4', title: 'Transfer & Renew', desc: 'Travel to Thimphu with a spa afternoon.' },
      { day: 'Day 5', title: 'Wellness Day', desc: 'Yoga, massage and free time.' },
      { day: 'Day 6', title: 'Departure', desc: 'Transfer to Paro airport for your onward flight.' },
    ],
  },
  'valley-vinyasa-journey': {
    name: 'Valley Vinyasa Journey',
    tour: 'Yoga Tours',
    tourPath: '/yoga-tours',
    tagline: 'Eight days of flowing practice and valley exploration',
    heroImage: img('photo-1455587734955-081b22074882'),
    duration: '8 Days / 7 Nights',
    groupSize: '4\u201314 guests',
    bestSeason: 'Mar\u2013May & Sep\u2013Nov',
    overview:
      'Flow through Bhutan\u2019s valleys with energising vinyasa practice each day, paired with gentle exploration of temples, forests and villages. A balanced journey for those who like to move, breathe and discover.',
    pricingNote: allInclusive + ' Daily yoga classes and instruction included.',
    pricing: [
      { group: 'Solo Traveller', price: '$2,450', unit: 'per person' },
      { group: '2 Travellers', price: '$2,150', unit: 'per person' },
      { group: '3\u20135 Travellers', price: '$1,950', unit: 'per person' },
      { group: '6+ Travellers', price: '$1,800', unit: 'per person' },
    ],
    highlights: [
      'Daily vinyasa flow sessions',
      'Practice across multiple valleys',
      'Forest and temple exploration',
      'Breathwork and meditation',
      'Nourishing wellness meals',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Welcome and gentle opening flow.' },
      { day: 'Day 2', title: 'Paro Flow & Hike', desc: 'Morning vinyasa and Tiger\u2019s Nest.' },
      { day: 'Day 3', title: 'Paro to Thimphu', desc: 'City visit and evening practice.' },
      { day: 'Day 4', title: 'Dochula & Punakha', desc: 'High-pass session and valley transfer.' },
      { day: 'Day 5', title: 'Punakha Flow', desc: 'Riverside vinyasa and valley walk.' },
      { day: 'Day 6', title: 'Phobjikha Valley', desc: 'Practice amid glacial valley scenery.' },
      { day: 'Day 7', title: 'Return to Paro', desc: 'Closing practice and reflection.' },
      { day: 'Day 8', title: 'Departure', desc: 'Transfer to Paro airport for your onward flight.' },
    ],
  },

  // ============ Food Tours ============
  'flavours-of-bhutan': {
    name: 'Flavours of Bhutan',
    tour: 'Food Tours',
    tourPath: '/food-tours',
    tagline: 'Six delicious days of tastings, markets and cooking',
    heroImage: img('photo-1571536802807-30451e3955d8'),
    duration: '6 Days / 5 Nights',
    groupSize: '2\u201312 foodies',
    bestSeason: 'Year-round',
    overview:
      'Eat your way through the western valleys on this flavour-packed journey. From fiery ema datshi to butter tea and farmhouse feasts, you\u2019ll taste the real Bhutan while browsing colourful markets and joining hands-on cooking sessions.',
    pricingNote: allInclusive + ' Tastings and cooking classes included.',
    pricing: [
      { group: 'Solo Traveller', price: '$1,750', unit: 'per person' },
      { group: '2 Travellers', price: '$1,550', unit: 'per person' },
      { group: '3\u20135 Travellers', price: '$1,400', unit: 'per person' },
      { group: '6+ Travellers', price: '$1,300', unit: 'per person' },
    ],
    highlights: [
      'Iconic ema datshi (chilli & cheese)',
      'Thimphu weekend market',
      'Hands-on cooking class',
      'Farmhouse feast and ara tasting',
      'Red rice and buckwheat dishes',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Welcome dinner of Bhutanese classics.' },
      { day: 'Day 2', title: 'Paro Flavours', desc: 'Market visit and a farmhouse cooking class.' },
      { day: 'Day 3', title: 'Paro to Thimphu', desc: 'Explore the famous weekend market.' },
      { day: 'Day 4', title: 'Thimphu Food Walk', desc: 'Street food, cafes and a cheese tasting.' },
      { day: 'Day 5', title: 'Punakha Feast', desc: 'Valley produce and a riverside lunch.' },
      { day: 'Day 6', title: 'Departure', desc: 'Transfer to Paro airport for your onward flight.' },
    ],
  },
  'farm-to-table-journey': {
    name: 'Farm to Table Journey',
    tour: 'Food Tours',
    tourPath: '/food-tours',
    tagline: 'Seven days from the field to the farmhouse kitchen',
    heroImage: img('photo-1605640840605-14ac1855827b'),
    duration: '7 Days / 6 Nights',
    groupSize: '2\u201312 foodies',
    bestSeason: 'Year-round',
    overview:
      'Get your hands dirty on this farm-to-table adventure, harvesting produce, learning age-old recipes and sharing meals with Bhutanese families. A warm, authentic immersion in the country\u2019s food culture and rural life.',
    pricingNote: allInclusive + ' Farm visits and cooking classes included.',
    pricing: [
      { group: 'Solo Traveller', price: '$2,050', unit: 'per person' },
      { group: '2 Travellers', price: '$1,750', unit: 'per person' },
      { group: '3\u20135 Travellers', price: '$1,600', unit: 'per person' },
      { group: '6+ Travellers', price: '$1,450', unit: 'per person' },
    ],
    highlights: [
      'Harvest produce on local farms',
      'Family farmhouse cooking',
      'Traditional recipes and techniques',
      'Cheese, ara and honey tastings',
      'Shared meals with locals',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Welcome and farmhouse dinner.' },
      { day: 'Day 2', title: 'Farm Morning', desc: 'Harvest and cook a traditional lunch.' },
      { day: 'Day 3', title: 'Paro to Thimphu', desc: 'Market sourcing and a cooking session.' },
      { day: 'Day 4', title: 'Thimphu Tastings', desc: 'Cheese, butter tea and street food.' },
      { day: 'Day 5', title: 'Punakha Valley', desc: 'Rice terraces and a riverside feast.' },
      { day: 'Day 6', title: 'Cooking Finale', desc: 'Cook your favourite dishes to take home.' },
      { day: 'Day 7', title: 'Departure', desc: 'Transfer to Paro airport for your onward flight.' },
    ],
  },
  'bhutanese-culinary-trail': {
    name: 'Bhutanese Culinary Trail',
    tour: 'Food Tours',
    tourPath: '/food-tours',
    tagline: 'Eight days tasting across the valleys',
    heroImage: img('photo-1528181304800-259b08848526'),
    duration: '8 Days / 7 Nights',
    groupSize: '2\u201312 foodies',
    bestSeason: 'Year-round',
    overview:
      'A grand culinary tour spanning multiple valleys, each with its own specialities. From western chilli-and-cheese classics to the buckwheat dishes of Bumthang, this journey is a feast for curious palates.',
    pricingNote: allInclusive + ' Tastings and cooking classes included.',
    pricing: [
      { group: 'Solo Traveller', price: '$2,450', unit: 'per person' },
      { group: '2 Travellers', price: '$2,150', unit: 'per person' },
      { group: '3\u20135 Travellers', price: '$1,950', unit: 'per person' },
      { group: '6+ Travellers', price: '$1,800', unit: 'per person' },
    ],
    highlights: [
      'Regional specialities across valleys',
      'Bumthang buckwheat dishes',
      'Multiple cooking classes',
      'Local markets and farms',
      'Ara and honey tastings',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Welcome dinner and orientation.' },
      { day: 'Day 2', title: 'Paro Tastings', desc: 'Market and farmhouse cooking.' },
      { day: 'Day 3', title: 'Paro to Thimphu', desc: 'Weekend market and food walk.' },
      { day: 'Day 4', title: 'Thimphu to Punakha', desc: 'Valley produce and riverside meal.' },
      { day: 'Days 5\u20136', title: 'Central Flavours', desc: 'Travel to Bumthang for buckwheat, cheese and honey.' },
      { day: 'Day 7', title: 'Return West', desc: 'Final tastings on the way back.' },
      { day: 'Day 8', title: 'Departure', desc: 'Transfer to Paro airport for your onward flight.' },
    ],
  },

  // ============ Biking Tours ============
  'western-valleys-cycling': {
    name: 'Western Valleys Cycling',
    tour: 'Biking Tours',
    tourPath: '/biking-tours',
    tagline: 'Seven days of road and trail through the western valleys',
    heroImage: img('photo-1464822759023-fed622ff2c3b'),
    duration: '7 Days / 6 Nights',
    groupSize: '2\u201310 riders',
    bestSeason: 'Mar\u2013May & Sep\u2013Nov',
    overview:
      'Pedal between Paro, Thimphu and Punakha on a mix of quiet paved roads and gentle trails. Climb to prayer-flag passes, roll through pine forest and stop at dzongs and villages, with a support vehicle always at hand.',
    pricingNote: allInclusive + ' Quality bikes, helmets and support vehicle included.',
    pricing: [
      { group: '2 Riders', price: '$2,350', unit: 'per person' },
      { group: '3\u20135 Riders', price: '$2,100', unit: 'per person' },
      { group: '6+ Riders', price: '$1,950', unit: 'per person' },
    ],
    highlights: [
      'Ride over the Dochula Pass',
      'Quiet valley roads and trails',
      'Dzong and village stops',
      'Forest descents',
      'Full support vehicle',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Bike fitting and warm-up ride.' },
      { day: 'Day 2', title: 'Paro Valley Ride', desc: 'Back roads and a Tiger\u2019s Nest hike.' },
      { day: 'Day 3', title: 'Paro to Thimphu', desc: 'Ride and transfer to the capital.' },
      { day: 'Day 4', title: 'Dochula Climb', desc: 'Climb the pass and a long forest descent.' },
      { day: 'Day 5', title: 'Punakha Trails', desc: 'Valley-floor riding and dzong visit.' },
      { day: 'Day 6', title: 'Return to Paro', desc: 'Final ride and transfer.' },
      { day: 'Day 7', title: 'Departure', desc: 'Transfer to Paro airport for your onward flight.' },
    ],
  },
  'dochula-mountain-biking': {
    name: 'Dochula Mountain Biking',
    tour: 'Biking Tours',
    tourPath: '/biking-tours',
    tagline: 'Six days of forest singletrack and big descents',
    heroImage: img('photo-1519681393784-d120267933ba'),
    duration: '6 Days / 5 Nights',
    groupSize: '2\u20138 riders',
    bestSeason: 'Mar\u2013May & Sep\u2013Nov',
    overview:
      'For mountain bikers, the trails around Dochula offer thrilling forest singletrack and long descents with Himalayan views. This trip focuses on the dirt, with shuttle support to maximise your time on the best trails.',
    pricingNote: allInclusive + ' Mountain bikes, protection and support vehicle included.',
    pricing: [
      { group: '2 Riders', price: '$2,050', unit: 'per person' },
      { group: '3\u20135 Riders', price: '$1,850', unit: 'per person' },
      { group: '6+ Riders', price: '$1,700', unit: 'per person' },
    ],
    highlights: [
      'Forest singletrack near Dochula',
      'Long, scenic descents',
      'Shuttle-assisted riding',
      'Himalayan trail views',
      'Skills coaching available',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Bike setup and warm-up trail.' },
      { day: 'Day 2', title: 'Paro to Thimphu', desc: 'Transfer and skills session.' },
      { day: 'Day 3', title: 'Dochula Trails', desc: 'Full day of forest singletrack.' },
      { day: 'Day 4', title: 'Big Descents', desc: 'Shuttle-assisted descents toward Punakha.' },
      { day: 'Day 5', title: 'Return Ride', desc: 'Final trails and transfer to Paro.' },
      { day: 'Day 6', title: 'Departure', desc: 'Transfer to Paro airport for your onward flight.' },
    ],
  },
  'central-bhutan-bike-tour': {
    name: 'Central Bhutan Bike Tour',
    tour: 'Biking Tours',
    tourPath: '/biking-tours',
    tagline: 'Nine days riding pass to pass into central Bhutan',
    heroImage: img('photo-1540541338287-41700207dee6'),
    duration: '9 Days / 8 Nights',
    groupSize: '2\u201310 riders',
    bestSeason: 'Mar\u2013May & Sep\u2013Nov',
    overview:
      'A bigger adventure for keen cyclists, crossing multiple mountain passes as you ride from the western valleys deep into central Bhutan. Long climbs, exhilarating descents and ever-changing scenery reward your effort.',
    pricingNote: allInclusive + ' Quality bikes, helmets and support vehicle included.',
    pricing: [
      { group: '2 Riders', price: '$2,950', unit: 'per person' },
      { group: '3\u20135 Riders', price: '$2,650', unit: 'per person' },
      { group: '6+ Riders', price: '$2,450', unit: 'per person' },
    ],
    highlights: [
      'Multiple high mountain passes',
      'Long, scenic descents',
      'Ride into central Bhutan',
      'Dzongs and villages en route',
      'Full support crew',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Bike fitting and warm-up.' },
      { day: 'Day 2', title: 'Paro to Thimphu', desc: 'Valley ride and transfer.' },
      { day: 'Day 3', title: 'Dochula to Punakha', desc: 'Climb the pass and descend to Punakha.' },
      { day: 'Days 4\u20135', title: 'Toward Trongsa', desc: 'Cross Pele La with long mountain stages.' },
      { day: 'Days 6\u20137', title: 'Central Valleys', desc: 'Ride through Trongsa and Bumthang scenery.' },
      { day: 'Day 8', title: 'Return Transfer', desc: 'Travel back toward Paro.' },
      { day: 'Day 9', title: 'Departure', desc: 'Transfer to Paro airport for your onward flight.' },
    ],
  },

  // ============ Motorcycle Tours ============
  'thunder-dragon-ride': {
    name: 'Thunder Dragon Ride',
    tour: 'Motorcycle Tours',
    tourPath: '/motorcycle-tours',
    tagline: 'Nine days riding the highlights of western Bhutan',
    heroImage: img('photo-1519681393784-d120267933ba'),
    duration: '9 Days / 8 Nights',
    groupSize: '2\u201310 riders',
    bestSeason: 'Mar\u2013May & Sep\u2013Nov',
    overview:
      'Throttle through the western valleys on this classic Himalayan motorcycle tour. Ride winding highways over prayer-flag passes, between ancient dzongs and into warm river valleys, with a support vehicle and expert lead rider every kilometre of the way.',
    pricingNote: allInclusive + ' Motorcycle hire, fuel, support vehicle and lead rider included.',
    pricing: [
      { group: '2 Riders', price: '$3,250', unit: 'per person' },
      { group: '3\u20135 Riders', price: '$2,950', unit: 'per person' },
      { group: '6+ Riders', price: '$2,750', unit: 'per person' },
    ],
    highlights: [
      'Ride over the Dochula Pass',
      'Winding Himalayan highways',
      'Dzongs and river valleys',
      'Support vehicle and lead rider',
      'Tiger\u2019s Nest visit',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Bike handover and briefing.' },
      { day: 'Day 2', title: 'Paro Shakedown', desc: 'Warm-up ride and Tiger\u2019s Nest hike.' },
      { day: 'Day 3', title: 'Paro to Thimphu', desc: 'Ride to the capital with city time.' },
      { day: 'Day 4', title: 'Dochula to Punakha', desc: 'Cross the pass to the warm valley.' },
      { day: 'Day 5', title: 'Punakha Ride', desc: 'Explore valley roads and the dzong.' },
      { day: 'Days 6\u20137', title: 'Phobjikha Loop', desc: 'Ride to the glacial crane valley and back.' },
      { day: 'Day 8', title: 'Return to Paro', desc: 'Final ride west.' },
      { day: 'Day 9', title: 'Departure', desc: 'Transfer to Paro airport for your onward flight.' },
    ],
  },
  'himalayan-passes-motorcycle-tour': {
    name: 'Himalayan Passes Motorcycle Tour',
    tour: 'Motorcycle Tours',
    tourPath: '/motorcycle-tours',
    tagline: 'Eleven days conquering Bhutan\u2019s legendary high passes',
    heroImage: img('photo-1483728642387-6c3bdd6c93e5'),
    duration: '11 Days / 10 Nights',
    groupSize: '2\u201310 riders',
    bestSeason: 'Mar\u2013May & Sep\u2013Nov',
    overview:
      'A pass-bagging epic for serious riders, climbing over a string of Bhutan\u2019s highest motorable passes as you ride from the western valleys into central Bhutan. Endless switchbacks, big skies and unforgettable scenery.',
    pricingNote: allInclusive + ' Motorcycle hire, fuel, support vehicle and lead rider included.',
    pricing: [
      { group: '2 Riders', price: '$3,950', unit: 'per person' },
      { group: '3\u20135 Riders', price: '$3,550', unit: 'per person' },
      { group: '6+ Riders', price: '$3,300', unit: 'per person' },
    ],
    highlights: [
      'Multiple high motorable passes',
      'Endless Himalayan switchbacks',
      'Chele La, the highest road pass',
      'Central Bhutan scenery',
      'Full mechanical support',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Bike handover and briefing.' },
      { day: 'Day 2', title: 'Chele La Pass', desc: 'Ride to Bhutan\u2019s highest road pass and Haa.' },
      { day: 'Day 3', title: 'Paro to Thimphu', desc: 'Highway ride to the capital.' },
      { day: 'Day 4', title: 'Dochula to Punakha', desc: 'Cross the pass to Punakha.' },
      { day: 'Days 5\u20136', title: 'Pele La to Trongsa', desc: 'Long pass-crossing stages into central Bhutan.' },
      { day: 'Days 7\u20138', title: 'Bumthang Valleys', desc: 'Ride the sacred valleys and Yotong La.' },
      { day: 'Days 9\u201310', title: 'Ride West', desc: 'Re-cross the passes back toward Paro.' },
      { day: 'Day 11', title: 'Departure', desc: 'Transfer to Paro airport for your onward flight.' },
    ],
  },
  'east-west-motorcycle-expedition': {
    name: 'East-West Motorcycle Expedition',
    tour: 'Motorcycle Tours',
    tourPath: '/motorcycle-tours',
    tagline: 'Fourteen days riding the length of the kingdom',
    heroImage: img('photo-1454496522488-7a8e488e8606'),
    duration: '14 Days / 13 Nights',
    groupSize: '2\u20138 riders',
    bestSeason: 'Mar\u2013Apr & Oct\u2013Nov',
    overview:
      'The ultimate Bhutan motorcycle expedition, traversing the entire country from the western valleys to the remote east. Crossing pass after pass through ever-wilder scenery, this is a true rider\u2019s odyssey across the Thunder Dragon Kingdom.',
    pricingNote: allInclusive + ' Motorcycle hire, fuel, support vehicle and lead rider included.',
    pricing: [
      { group: '2 Riders', price: '$4,950', unit: 'per person' },
      { group: '3\u20135 Riders', price: '$4,500', unit: 'per person' },
      { group: '6+ Riders', price: '$4,200', unit: 'per person' },
    ],
    highlights: [
      'Ride the full length of Bhutan',
      'A dozen Himalayan passes',
      'Remote eastern highways',
      'Diverse landscapes and cultures',
      'Full support and mechanic',
    ],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Paro', desc: 'Bike handover and briefing.' },
      { day: 'Days 2\u20133', title: 'Western Valleys', desc: 'Chele La, Thimphu and Dochula to Punakha.' },
      { day: 'Days 4\u20136', title: 'Central Bhutan', desc: 'Pele La, Trongsa and the Bumthang valleys.' },
      { day: 'Days 7\u20139', title: 'Into the East', desc: 'Cross Thrumshing La toward Mongar and Trashigang.' },
      { day: 'Days 10\u201312', title: 'Eastern Highways', desc: 'Explore the remote far east of the kingdom.' },
      { day: 'Day 13', title: 'Final Stage', desc: 'Last ride and celebration dinner.' },
      { day: 'Day 14', title: 'Departure', desc: 'Fly out from the east or transfer onward.' },
    ],
  },
}
